service:

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
